//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ProSaver.rc
//
#define MANIFEST_RESOURCE_ID            1
#define IDS_STRING                      1
#define IDI_MAINICON                    101
#define IDD_MAINDLG_SAVERS              102
#define IDD_MAINDLG_PLAYBACK            103
#define IDD_SAVERINFO                   104
#define IDD_EDITTHEMES                  105
#define IDD_NEWTHEME                    106
#define IDD_RENAMETHEME                 107
#define IDD_CHANGEMUSIC                 108
#define IDD_MUSICMGR                    109
#define IDD_PREFS                       110
#define IDD_ABOUT                       111
#define IDD_PURCHASE                    112
#define IDB_RATINGS                     113
#define IDB_DIMRATINGS                  114
#define IDB_COMPUTER                    115
#define IDB_FOLDER                      116
#define IDB_FOLDERLT                    117
#define IDB_BACKBTN                     118
#define IDB_DIMBACKBTN                  119
#define IDB_UPBTN                       120
#define IDB_DIMUPBTN                    121
#define IDB_SPLASH                      122
#define IDB_SCREEN                      123
#define IDB_ABOUTBMP                    124
#define IDB_WBSLOGO                     125
#define IDB_ASPLOGO                     126
#define IDB_PSBUY                       127
#define IDB_CCARDS1                     128
#define IDB_CCARDS2                     129
#define IDR_NEWSELSND                   130
#define IDR_ADDSAVERSND                 131
#define IDR_CLEARSELSND                 132
#define IDR_SORTSND                     133
#define IDR_DELALLSND                   134
#define IDR_NULLSND                     135
#define IDR_NULLMP3                     138
#define IDB_SAVERIMG1                   139
#define IDB_SAVERIMG2                   140
#define IDD_DXINIT                      142
#define IDD_WELCOMEDLG                  143
#define IDB_WELCOME                     144
#define IDC_APPLY                       1001
#define IDC_SAVERLIST                   1002
#define IDC_CLEARSELBTN                 1003
#define IDC_ADDSAVERBTN                 1004
#define IDC_CURRPLIST                   1005
#define IDC_PLISTSORTCBX                1006
#define IDC_PLISTUPBTN                  1007
#define IDC_PLISTTOPBTN                 1008
#define IDC_PLISTDOWNBTN                1009
#define IDC_PLISTBOTTOMBTN              1010
#define IDC_PLISTDELBTN                 1011
#define IDC_PLISTCLRBTN                 1012
#define IDC_PLISTSAVEBTN                1013
#define IDC_PLISTLOADBTN                1014
#define IDC_SAVERINFO                   1015
#define IDC_SETTINGSBTN                 1016
#define IDC_PREVIEWBTN                  1017
#define IDC_EDITINFOBTN                 1018
#define IDC_SHOWPREVIEWCHK              1019
#define IDC_PREVIEWWND                  1020
#define IDC_SAVERINFOICON               1021
#define IDC_SAVERNAME                   1022
#define IDC_THEMESELBOX                 1023
#define IDC_EDITTHEMESBTN               1024
#define IDC_RATINGSELBOX                1025
#define IDC_EDITHELPBTN                 1026
#define IDC_MUSICSELBOX                 1027
#define IDC_MUSICBROWSEBTN              1028
#define IDC_MUSICCYCLERAD               1029
#define IDC_MUSICSHUFFLERAD             1030
#define IDC_SAVERDESC                   1031
#define IDC_SAVERDESCEDT                1032
#define IDC_DISABLEPREVCHK              1033
#define IDC_THEMESLIST                  1034
#define IDC_NEWTHEMEBTN                 1035
#define IDC_DELTHEMEBTN                 1036
#define IDC_RENAMETHEMEBTN              1037
#define IDC_DEFTHEMESBTN                1038
#define IDC_THEMESHELPBTN               1039
#define IDC_NEWTHEMEEDT                 1040
#define IDC_RENAMETHEMEEDT              1041
#define IDC_LOADAUDFILEBTN              1042
#define IDC_LOADPLISTBTN                1043
#define IDC_CLEARMUSBTN                 1044
#define IDC_EDITAUDIOBTN                1045
#define IDC_CHGMUSHELPBTN               1046
#define IDC_ONESVRRAD                   1047
#define IDC_MULTISVRRAD                 1048
#define IDC_SHOWSVRTXT                  1049
#define IDC_SHOWSVREDT                  1050
#define IDC_SHOWSVRMINTXT               1051
#define IDC_SVRCYCLERAD                 1052
#define IDC_SVRSHUFFLERAD               1053
#define IDC_ENABLEHKEYSCBX              1054
#define IDC_STARTSVRTXT                 1055
#define IDC_STARTSVRHKY                 1056
#define IDC_SKIPSVRTXT                  1057
#define IDC_SKIPSVRHKY                  1058
#define IDC_OPENPSTXT                   1059
#define IDC_OPENPSHKY                   1060
#define IDC_CLRSCREENCBX                1061
#define IDC_NOMUSICCBX                  1062
#define IDC_OPENTHEMESBTN               1063
#define IDC_OPENAUDIOBTN                1064
#define IDC_ADVWARNTXT                  1065
#define IDC_SHOWADVBTN                  1066
#define IDC_SPATHSTATIC                 1067
#define IDC_SEARCHLIST                  1068
#define IDC_ADDPATHBTN                  1069
#define IDC_CHANGEPATHBTN               1070
#define IDC_DELETEPATHBTN               1071
#define IDC_SYSTRAYCHK                  1072
#define IDC_KEEPCURCHK                  1073
#define IDC_HIDEADVCHK                  1074
#define IDC_ERRLOGSTATIC                1075
#define IDC_ERRORLOGCHK                 1076
#define IDC_MAXLINESTXT                 1077
#define IDC_MAXLINESEDT                 1078
#define IDC_ERRORLOGBTN                 1079
#define IDC_RESETMSGBTN                 1080
#define IDC_HIDEADVBTN                  1081
#define IDC_HISTORYCBX                  1082
#define IDC_FILEBACKBTN                 1083
#define IDC_FILEUPBTN                   1084
#define IDC_FILELIST                    1085
#define IDC_FILETYPECBX                 1086
#define IDC_CLEARAUDIOSELBTN            1087
#define IDC_ADDAUDIOFILEBTN             1088
#define IDC_AUDIOPLIST                  1089
#define IDC_AUDIOPLISTSORTCBX           1090
#define IDC_AUDIOPLISTUPBTN             1091
#define IDC_AUDIOPLISTTOPBTN            1092
#define IDC_AUDIOPLISTDOWNBTN           1093
#define IDC_AUDIOPLISTBOTTOMBTN         1094
#define IDC_AUDIOPLISTDELBTN            1095
#define IDC_AUDIOPLISTCLRBTN            1096
#define IDC_AUDIOPLISTSAVEBTN           1097
#define IDC_AUDIOPLISTLOADBTN           1098
#define IDC_AUDIOINFO                   1099
#define IDC_PLAYBTN                     1100
#define IDC_PAUSEBTN                    1101
#define IDC_STOPBTN                     1102
#define IDC_FULLREWBTN                  1103
#define IDC_REWBTN                      1104
#define IDC_FWDBTN                      1105
#define IDC_AUDIOPOSTXT                 1106
#define IDC_AUDIOPOSSLD                 1107
#define IDC_ENABLEPBCCHK                1108
#define IDC_NEXTHKYTXT                  1109
#define IDC_NEXTHKY                     1110
#define IDC_VOLUPHKYTXT                 1111
#define IDC_VOLUPHKY                    1112
#define IDC_VOLDNHKYTXT                 1113
#define IDC_VOLDNHKY                    1114
#define IDC_MUTEHKYTXT                  1115
#define IDC_MUTEHKY                     1116
#define IDC_WINSYNTHRAD                 1117
#define IDC_DXSYNTHRAD                  1118
#define IDC_DXFXTXT                     1119
#define IDC_REVERBCHK                   1120
#define IDC_CHORUSCHK                   1121
#define IDC_MUSMANHELPBTN               1122
#define IDC_INSTALLDXBTN                1123
#define IDC_PLAYSFXCHK                  1124
#define IDC_SHOWTOOLTIPSCHK             1125
#define IDC_SPLASHSCRNCHK               1126
#define IDC_SAVERLISTDETCHK             1127
#define IDC_RATINGIMGSCHK               1128
#define IDC_SLISTPOPUPCHK               1129
#define IDC_PLISTPOPUPCHK               1130
#define IDC_PREFSHELPBTN                1131
#define IDC_ABOUTBMP                    1132
#define IDC_PSMGRTXT                    1133
#define IDC_WBSOFTBMP                   1134
#define IDC_ASPLOGOBMP                  1135
#define IDC_VIEWLICBTN                  1136
#define IDC_VIEWREADMEBTN               1137
#define IDC_TRIALDAYSTXT                1138
#define IDC_CCARDS1BMP                  1139
#define IDC_CCARDS2BMP                  1140
#define IDC_PSBUYBMP                    1141
#define IDC_ORDERBTN                    1142
#define IDC_MAILFORMBTN                 1143
#define IDC_TUTORIALLBX                 1144
#define IDC_SHOWTUTORIALBTN             1145
#define IDC_SHOWWELCOMECHK              1146
#define IDC_CLOSEWNDBTN                 1147

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
